/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.FoodQualityAdminWorkArea;

import business.ApplicationSystem;
import catering.system.Users.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author nishipancholi
 */
public class FoodQualityAdminMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodProdAdminMainJPanel
     */
    public FoodQualityAdminMainJPanel() {
        initComponents();
    }

    public FoodQualityAdminMainJPanel(JPanel userProcessContainer, UserAccount account, ApplicationSystem business) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCourseHeaderLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCourseHeaderLabel.setFont(new java.awt.Font("Kannada MN", 1, 20)); // NOI18N
        addCourseHeaderLabel.setText("FOOD QUALITY ADMIN PORTAL");
        add(addCourseHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 350, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCourseHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
