/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.FoodWarehouseAdminWorkArea;

import business.ApplicationSystem;
import catering.system.FoodWarehouseOrganization.Inventory;
import catering.system.FoodWarehouseOrganization.InventoryManager;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class InventoryStoreManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryStoreManagementJPanel
     */
    
    JPanel userProcessContainer;
    private static ApplicationSystem system;
    DefaultTableModel storeListTableModel;

    public InventoryStoreManagementJPanel() {
        initComponents();
    }
    public InventoryStoreManagementJPanel(JPanel userProcessContainer, ApplicationSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        storeListTableModel = (DefaultTableModel)storeListTable.getModel();
        showComboBoxesList();
        viewGroceryList();
    }
    
    public void viewGroceryList() {
        if (system.getInventoryDirectory().getStoreList().size() > 0) {
            for (int i = 0; i < system.getInventoryDirectory().getStoreList().size(); i++) {
                storeListTableModel.addRow(new Object[]{
                    system.getInventoryDirectory().getStoreList().get(i).getName(),
                    system.getInventoryDirectory().getStoreList().get(i).getManagerDetails().getName(),
                    system.getInventoryDirectory().getStoreList().get(i).getLocation(),
                    system.getInventoryDirectory().getStoreList().get(i).getPhone(),
                });
            }
        }
    }

    
    
    public void showComboBoxesList() {
        managerListCombobox.removeAllItems();
        ArrayList<InventoryManager> managerslist = this.system.getEnterpriseDirectory().getInventoryManagerDirectory().getInventoryManagerList();
        System.out.println(managerslist+" managerslist");
         if(managerslist.size() > 0){
             for (InventoryManager im :managerslist){
                 managerListCombobox.addItem(im);
             }
        }
        else{
            System.out.println("Empty List");
        }
        /*for (int i = 0; i < system.getInventoryManagerDirectory().getInventoryManagerList().size(); i++) {
            managerListCombobox.addItem(system.getInventoryManagerDirectory().getInventoryManagerList().get(i).getName());
            updateManagerListCombobox.addItem(system.getInventoryManagerDirectory().getInventoryManagerList().get(i).getName());
        }*/
    }
    
  
    
    public InventoryManager getCurrentManager(String name) {
        for (int i = 0; i < system.getInventoryManagerDirectory().getInventoryManagerList().size(); i++) {
            if (system.getInventoryManagerDirectory().getInventoryManagerList().get(i).getName().equals(name)) {
                return system.getInventoryManagerDirectory().getInventoryManagerList().get(i);
            }
        }
        return null;
    }
    
    public Boolean validateFields(String address, String phone, String name) {
        if(phone.isEmpty() || name.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Error message", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(phone.length() != 10) {
            JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits","Error message", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!phone.matches("^[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "Phone Number must have digits only","Error message", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storeNameJLabel = new javax.swing.JLabel();
        storeNameText = new javax.swing.JTextField();
        addStoreButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeListTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        ManagerJLabel = new javax.swing.JLabel();
        managerListCombobox = new javax.swing.JComboBox();
        phoneJLabel = new javax.swing.JLabel();
        locationJLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 180, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Item");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 120, 21));

        storeNameJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        storeNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        storeNameJLabel.setText("Name");
        add(storeNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 50, 30));

        storeNameText.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        storeNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeNameTextActionPerformed(evt);
            }
        });
        add(storeNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 150, 30));

        addStoreButton.setBackground(new java.awt.Color(255, 203, 162));
        addStoreButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addStoreButton.setText("Add ");
        addStoreButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStoreButtonActionPerformed(evt);
            }
        });
        add(addStoreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 130, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Items");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 110, 24));

        storeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Manager", "Location", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(storeListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 540, 188));

        btnBack.setBackground(new java.awt.Color(255, 203, 162));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 133, 40));

        ManagerJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ManagerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ManagerJLabel.setText("Manager Name");
        add(ManagerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 110, 30));

        managerListCombobox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        managerListCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        managerListCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerListComboboxActionPerformed(evt);
            }
        });
        add(managerListCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 150, 30));

        phoneJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        phoneJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneJLabel.setText("Phone");
        add(phoneJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 50, 30));

        locationJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        locationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        locationJLabel.setText("Location");
        add(locationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 30));

        locationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        locationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextFieldActionPerformed(evt);
            }
        });
        add(locationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 150, 30));

        phoneTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, 30));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Manage Inventory Store");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 510, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void storeNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeNameTextActionPerformed

    private void addStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStoreButtonActionPerformed
        // TODO add your handling code here:
        if(managerListCombobox.getSelectedItem() == null || managerListCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,"Select a value from dropdown of Inventory to update","Error message", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!validateFields(locationTextField.getText(), phoneTextField.getText(), storeNameText.getText())) {
            return;
        }
        for (int i = 0; i < system.getInventoryDirectory().getStoreList().size(); i++) {
            if(system.getInventoryDirectory().getStoreList().get(i).getName() == null ? storeNameText.getText() == null : system.getInventoryDirectory().getStoreList().get(i).getName().equals(storeNameText.getText())){
                JOptionPane.showMessageDialog(null,"Inventory Already Present", "Error message" ,JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        String managerSelectedItem = (String) managerListCombobox.getSelectedItem();

        //String selectedItem = (String) storeListCombobox.getSelectedItem();

        InventoryManager rm = getCurrentManager(managerSelectedItem);
        system.getInventoryDirectory().createInventoryStore(storeNameText.getText(), rm, phoneTextField.getText(), locationTextField.getText());
        System.out.println("Inventory Store Added ....");
        JOptionPane.showMessageDialog(this, "Inventory store added successfully");
        

        storeListTableModel.addRow(new Object[]{
            storeNameText.getText(),
            managerSelectedItem,
            locationTextField.getText(),
            phoneTextField.getText()
        });
        storeNameText.setText("");
        locationTextField.setText("");
        phoneTextField.setText("");

        managerListCombobox.setSelectedItem(null);
    }//GEN-LAST:event_addStoreButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        FoodWareHouseAdminMainJPanel dm= new FoodWareHouseAdminMainJPanel(userProcessContainer, system);
        userProcessContainer.add("FoodWareHouseAdminMainJPanel",dm);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void managerListComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerListComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerListComboboxActionPerformed

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManagerJLabel;
    private javax.swing.JButton addStoreButton;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationJLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JComboBox managerListCombobox;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTable storeListTable;
    private javax.swing.JLabel storeNameJLabel;
    private javax.swing.JTextField storeNameText;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
