/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.FoodProdAdminWorkArea;

import business.ApplicationSystem;
import catering.system.FoodProdOrganization.Menu;
import catering.system.Users.UserAccount;
import catering.system.validations.Validate;
import catering.system.validations.ValidateNumbers;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class AddMenuJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    ApplicationSystem system;
    DefaultTableModel viewTableModel;
    UserAccount ua;
    Validate validate;

    /**
     * Creates new form AddMenuJPanel
     */
    public AddMenuJPanel() {
        initComponents();
    }

    AddMenuJPanel(JPanel userProcessContainer, UserAccount ua, ApplicationSystem system) {
        initComponents();
        this.system=system;
        this.ua = ua;
        this.userProcessContainer=userProcessContainer;
        this.validate=new Validate();
        this.viewTableModel= (DefaultTableModel) menuTable.getModel();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        breakfastField = new javax.swing.JTextField();
        lunchField = new javax.swing.JTextField();
        dinnerField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        batchField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addMenuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        priceField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 180, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 203, 162));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 50));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel1.setText("Menu Creation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));
        add(breakfastField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 220, 30));
        add(lunchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 220, 30));
        add(dinnerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 220, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Choose Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Price Per Batch");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 20));
        add(batchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 220, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Breakfast");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 70, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Lunch");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 50, 20));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Dinner");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 20));

        addMenuButton.setBackground(new java.awt.Color(255, 203, 162));
        addMenuButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addMenuButton.setText("Add Menu");
        addMenuButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuButtonActionPerformed(evt);
            }
        });
        add(addMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 180, 50));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Breakfast", "Lunch", "Dinner", "Batch", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 500, 310));
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 220, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Batch");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 220, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void populate()
    {
        viewTableModel.setRowCount(0);
        ArrayList<Menu> applications=this.system.getEnterpriseDirectory().getMenuList();
        System.out.println(applications);
        if(applications.size()>0){
            for (Menu app:applications){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(app.getDate());
                Object row[]= new Object[6];
                row[0]=date;
                row[1]=app;
                row[2]=app.getLunch();
                row[3]=app.getDinner();
                row[4]=app.getBatch();
                row[5]=app.getPrice();
                
                viewTableModel.addRow(row);
            }
        }
        else{
            System.out.println("Empty List");
        }
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CateringManagerMainJPanel dm= new CateringManagerMainJPanel(userProcessContainer, ua,system);
        userProcessContainer.add("manageHospitalsJPanel",dm);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void addMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuButtonActionPerformed
        // TODO add your handling code here:
        try{
        Boolean isValidBatch=validate.checkNoNegativeZero(batchField.getText());
        Boolean isValidPrice=validate.checkNoNegativeZero(priceField.getText());
        Boolean isPriceValid = ValidateNumbers.verifyNumbers(priceField);
        Boolean isBatchValid = ValidateNumbers.verifyNumbers(batchField);
        if (!isPriceValid || !isBatchValid) {
            return;
        }
        if(!isValidBatch){
            return;
        }
        if(!isValidPrice){
            return;
        }
        Date menuDate= jDateChooser1.getDate();
      
        Menu employee = system.getEnterpriseDirectory().createMenu(menuDate, breakfastField.getText(), lunchField.getText(), dinnerField.getText(), Integer.valueOf(batchField.getText()), Float.valueOf(priceField.getText()));

        JOptionPane.showMessageDialog(null, "Menu added successfully");
        populate();
        breakfastField.setText("");
        lunchField.setText("");
        dinnerField.setText("");
        batchField.setText("");
        priceField.setText("");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "only int in batch float in price allowed");
            System.out.println("only int in batch float in price allowed");
        }
        
    }//GEN-LAST:event_addMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenuButton;
    private javax.swing.JTextField batchField;
    private javax.swing.JTextField breakfastField;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField dinnerField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lunchField;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField priceField;
    // End of variables declaration//GEN-END:variables
}
