/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.AdminWorkArea;

import business.ApplicationSystem;
import catering.system.Enterprise.Enterprise;
import catering.system.validations.Validate;
import catering.system.validations.ValidateStrings;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class AddEnterpriseJPanel extends javax.swing.JPanel {
    private ApplicationSystem system;
    JPanel container;
    DefaultTableModel entTableModel;
    public Enterprise selectedEnterprise;
    Validate valid;
    /**
     * Creates new form AddEnterpriseJPanel
     */
    public AddEnterpriseJPanel() {
        initComponents();
    }

    AddEnterpriseJPanel(ApplicationSystem system, JPanel container) {
        initComponents();
        this.system=system;
        this.container=container;
        this.entTableModel= (DefaultTableModel) entTable.getModel();
        this.valid=new Validate();
        populate();
    }
    
    public void populate(){
        entTableModel.setRowCount(0);
        ArrayList<Enterprise> enterpiseList=this.system.getEnterpriseDirectory().getEnterpriseList();
        if(enterpiseList.size()>0){
            for (Enterprise ent:enterpiseList){
                
                Object row[]= new Object[2];
                row[0]=ent;
                row[1]=ent.getEnterpriseName();
                
                entTableModel.addRow(row);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"No Enterprise Found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addEntButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        entTable = new javax.swing.JTable();
        updateEntButton = new javax.swing.JButton();
        viewEntButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewEnttypeField = new javax.swing.JTextField();
        viewEntNameField = new javax.swing.JTextField();
        deleteEnterpriseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 180, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Enterprise name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Service Enterprise", "Food Production Enterprise", "Food Quality Enterprise", "Food WareHouse Enterprise" }));
        add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 250, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel2.setText("Add Enterprise");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Enterprise type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, -1));

        addEntButton.setBackground(new java.awt.Color(255, 203, 162));
        addEntButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addEntButton.setText("Add Enterprise");
        addEntButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addEntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntButtonActionPerformed(evt);
            }
        });
        add(addEntButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 40));

        entTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Type", "Enterprise Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(entTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 190));

        updateEntButton.setBackground(new java.awt.Color(255, 203, 162));
        updateEntButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateEntButton.setText("Update Enterprise");
        updateEntButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateEntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEntButtonActionPerformed(evt);
            }
        });
        add(updateEntButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 240, 40));

        viewEntButton.setBackground(new java.awt.Color(255, 203, 162));
        viewEntButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        viewEntButton.setText("View Enterprise");
        viewEntButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEntButtonActionPerformed(evt);
            }
        });
        add(viewEntButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 190, 50));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Enterprise type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Enterprise name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, 30));

        viewEnttypeField.setEnabled(false);
        add(viewEnttypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 280, -1));
        add(viewEntNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 280, -1));

        deleteEnterpriseButton.setBackground(new java.awt.Color(255, 203, 162));
        deleteEnterpriseButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteEnterpriseButton.setText("Delete  Enterprise");
        deleteEnterpriseButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnterpriseButtonActionPerformed(evt);
            }
        });
        add(deleteEnterpriseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 190, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addEntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntButtonActionPerformed
        // TODO add your handling code here:
        String type=(String) typeComboBox.getSelectedItem();
        String name= nameField.getText();
        Boolean isNotEmptyNull= ValidateStrings.checkNullEmpty(name);
        for (int i = 0; i < system.getEnterpriseDirectory().getEnterpriseList().size(); i++) {
            if(system.getEnterpriseDirectory().getEnterpriseList().get(i).getEntType().equals(type)){
                JOptionPane.showMessageDialog(null,"Enterprise Already Present", "Error message" ,JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Boolean isValid = valid.checkName(name);
        if(isValid && isNotEmptyNull){
            system.getEnterpriseDirectory().createEnterprise(name,type);
            JOptionPane.showMessageDialog(null, "Enterprise created.");
            populate();
            nameField.setText("");
        }
    }//GEN-LAST:event_addEntButtonActionPerformed

    private void viewEntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEntButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = entTable.getSelectedRow();
        
        if(selectedRow>=0){
            
            selectedEnterprise = (Enterprise) entTable.getValueAt(selectedRow, 0);
            viewEnttypeField.setText(selectedEnterprise.getEntType());
            viewEntNameField.setText(selectedEnterprise.getEnterpriseName());
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select row");
        }
    }//GEN-LAST:event_viewEntButtonActionPerformed

    private void updateEntButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEntButtonActionPerformed
        // TODO add your handling code here:
        Boolean isValid=valid.checkName(viewEntNameField.getText());
        if(isValid){
            selectedEnterprise.setEnterpriseName(viewEntNameField.getText());
            JOptionPane.showMessageDialog(null,"Updated Enterprise Name!"); 
            populate();
        }
    }//GEN-LAST:event_updateEntButtonActionPerformed

    private void deleteEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = entTable.getSelectedRow();
        if(selectedRow>=0){
            selectedEnterprise= (Enterprise) entTable.getValueAt(selectedRow,0);
            this.system.getEnterpriseDirectory().deleteEnterprise(selectedEnterprise);
            JOptionPane.showMessageDialog(null,"Enterprise Deleted!");
            populate();
        }
        else{
            JOptionPane.showMessageDialog(null,"Any row selection is not done!");
        }
    }//GEN-LAST:event_deleteEnterpriseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntButton;
    private javax.swing.JButton deleteEnterpriseButton;
    private javax.swing.JTable entTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JButton updateEntButton;
    private javax.swing.JButton viewEntButton;
    private javax.swing.JTextField viewEntNameField;
    private javax.swing.JTextField viewEnttypeField;
    // End of variables declaration//GEN-END:variables
}
