/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.AdminWorkArea;

import business.ApplicationSystem;
import catering.system.UI.MainJFrame;
import catering.system.Useraccount.UserAccount;
import com.opencsv.CSVReader;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class OrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationJPanel
     */
    ApplicationSystem system;
    UserAccount userAccount;
    DefaultTableModel jobTableModel;
    
    public OrganizationJPanel() {
        initComponents();
    }

    OrganizationJPanel(ApplicationSystem system, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.jobTableModel = (DefaultTableModel) organizationTable.getModel();
        readCsvDataToTable();
    }

    
    public void readCsvDataToTable() {
        try {
            String filePath = "src/files/organization.csv";
            BufferedReader reader = new BufferedReader(new FileReader(filePath));
            CSVReader csvReader = new CSVReader(reader);
            List<String[]> rows = csvReader.readAll();

            for (String[] row : rows) {
                jobTableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 470, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
