/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.adminWorkArea;

import business.ApplicationSystem;
import catering.system.useraccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class ViewUsersJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private ApplicationSystem system;
    DefaultTableModel tableModel;

    /**
     * Creates new form viewUsersJPanel
     */
    public ViewUsersJPanel() {
        initComponents();
        this.tableModel = (DefaultTableModel) userTable.getModel();
        populateTable();
    }

    ViewUsersJPanel(ApplicationSystem system, UserAccount useraccount) {
        initComponents();
        this.system=system;
        this.useraccount=useraccount;
        this.tableModel = (DefaultTableModel) userTable.getModel();
        populateTable();
    }
    
    public void populateTable() {
        
        tableModel.setRowCount(0);
        for(UserAccount ua: this.system.getUserAccountDirectory().getUserAccountlist()) {
            
            Object[] row = new Object[2];
            

            row[0] = ua.getUsername();
            row[1] = ua.getRole();
            
            tableModel.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
