/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.ClientRegistrationWorkArea;

import business.ApplicationSystem;
import catering.system.FoodProdOrganization.Menu;
import catering.system.OrderManagement.ClientOrder;
import catering.system.Organization.ServiceEnterpriseOrganization.Client;
import catering.system.Users.UserAccount;
import catering.system.validations.Validate;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrunalipawar
 */
public class ClientWorkAreaJPanel extends javax.swing.JPanel {
    DefaultTableModel viewTableModel;
    DefaultTableModel orderTableModel;
    ApplicationSystem system;
    UserAccount ua;
    Menu selectedMenu;
    int quantity;
    Validate valid;
    

    /**
     * Creates new form ClientWorkAreaJPanel
     */
    public ClientWorkAreaJPanel() {
        initComponents();
    }

    public ClientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ApplicationSystem business) {
        initComponents();
        this.viewTableModel= (DefaultTableModel) menuTable.getModel();
        this.orderTableModel= (DefaultTableModel) orderTable.getModel();
        this.system=business;
        this.ua=account;
        this.valid=new Validate();
        this.selectedMenu=new Menu();
        populate();
        populateOrder();
        
    }
    
    public void populate()
    {
        viewTableModel.setRowCount(0);
        ArrayList<Menu> applications=this.system.getEnterpriseDirectory().getMenuList();
        System.out.println(applications);
        if(applications.size()>0){
            for (Menu app:applications){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(app.getDate());
                Object row[]= new Object[6];
                row[0]=date;
                row[1]=app;
                row[2]=app.getLunch();
                row[3]=app.getDinner();
                row[4]=app.getBatch();
                row[5]=app.getPrice();
                
                viewTableModel.addRow(row);
            }
        }
        else{
            System.out.println("Empty Menu");
        }
    }
    
    public void populateOrder()
    {
        orderTableModel.setRowCount(0);
        ArrayList<ClientOrder> applications=this.system.getEnterpriseDirectory().getClientOrderDirectory().getClientorderList();
        System.out.println(applications);
        if(applications.size()>0){
            for (ClientOrder app:applications){
                if(ua==app.getClient().getAccountDetails()){
                    Object row[]= new Object[4];
                    row[0]=app;
                    row[1]=app.getPrice();
                    row[2]=app.getStatus();
                    row[3]=app.getClient().getClientType();

                    orderTableModel.addRow(row);
                }
            }
        }
        else{
            System.out.println("Empty Menu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        priceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        QualityField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        cvvField = new javax.swing.JTextField();
        cardnoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 180, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        jLabel1.setText("Welcome to Meal Mate");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Breakfast", "Lunch", "Dinner", "Batch", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 500, 190));

        priceField.setEnabled(false);
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 250, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("CVV:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, 20));
        add(QualityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 250, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Quantity:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 20));

        placeOrderButton.setBackground(new java.awt.Color(255, 102, 102));
        placeOrderButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        placeOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderButton.setText("Place Order");
        placeOrderButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });
        add(placeOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 190, 40));
        add(cvvField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 250, -1));
        add(cardnoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 250, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, 20));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Card Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, 20));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Paid Money", "Order Status", "Client Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 190));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Make Payment");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 180, 50));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setText("~Place your order with Us!!!");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 370, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        try{
        int selectedRow = menuTable.getSelectedRow();
        boolean isValid= valid.checkNoNegativeZero(QualityField.getText());
        if(isValid){
        if(selectedRow>=0){
            
            selectedMenu = (Menu) menuTable.getValueAt(selectedRow, 1);
            int price=Integer.valueOf(QualityField.getText());
            this.quantity= price;
            if(selectedMenu.getBatch()<price){
                JOptionPane.showMessageDialog(null,"Sorry we do not have enough quantity of batches");
            }
            else{
                float pricePerBatch=selectedMenu.getPrice();
                float totalPrice=pricePerBatch*price;
                priceField.setText(String.valueOf(totalPrice));
                JOptionPane.showMessageDialog(null,"Please Proceed to Payment to Place Order");
                QualityField.setText("");
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select row");
        }
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Should be an integer");
            System.out.println("Should be an integer");
        }
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        ArrayList<Client> clientList=this.system.getClientDirectory().getClientList();
        Client selectedClient= new Client();
        for(Client c:clientList){
            if(ua==c.getAccountDetails()){
                selectedClient=c;
            }
        }
        boolean isCardnoValid= valid.checkNoNegativeZero(cardnoField.getText());
        boolean isCvvValid= valid.checkNoNegativeZero(cvvField.getText());
        if(isCardnoValid && isCvvValid){
            ClientOrder corder=this.system.getEnterpriseDirectory().getClientOrderDirectory().createOrder(selectedMenu, Float.valueOf(priceField.getText()), selectedClient);
            System.out.print(corder+"corder");
            int batch = selectedMenu.getBatch();
            int newBatch= batch-quantity;
            selectedMenu.setBatch(newBatch);
            JOptionPane.showMessageDialog(null,"Payment Done");
            populate();
            populateOrder();
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Should be an integer");
            System.out.println("Should be an integer");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QualityField;
    private javax.swing.JTextField cardnoField;
    private javax.swing.JTextField cvvField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable menuTable;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTextField priceField;
    // End of variables declaration//GEN-END:variables
}
