/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package catering.system.UI.serviceEntAdminWorkArea;

import business.ApplicationSystem;
import catering.system.Enterprise.Enterprise;
import catering.system.Organization.Organization;
import catering.system.Organization.OrganizationDirectory;
import catering.system.Users.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class AddOrganizationJPanel extends javax.swing.JPanel {
    private ApplicationSystem system;
    private UserAccount useraccount;
    private Enterprise currentEnterprise;
    DefaultTableModel tableModel;

    /**
     * Creates new form AddOrganizationJPanel
     */
    public AddOrganizationJPanel() {
        initComponents();
    }

    AddOrganizationJPanel(ApplicationSystem system, UserAccount useraccount, Enterprise currentEnterprise) {
       initComponents();
       this.system=system;
       this.useraccount=useraccount;
       this.currentEnterprise=currentEnterprise;
       this.tableModel = (DefaultTableModel) orgTable.getModel();
       populate();
    }
    
    public void populate() {
        tableModel.setRowCount(0);
        ArrayList<Organization> orgDir=this.currentEnterprise.getOrganizationDirectory().getOrganizationList();
        for(Organization org:orgDir){
                Object[] row = new Object[2];
                row[0] = org.getType();
                row[1] = org;
                
                tableModel.addRow(row);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeComboBox = new javax.swing.JComboBox();
        organizationNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addOrganizationButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School", "Hospital", "Office", "Government" }));
        add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 220, -1));
        add(organizationNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 220, -1));

        jLabel1.setText("name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel2.setText("type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        addOrganizationButton.setText("Add Organization");
        addOrganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationButtonActionPerformed(evt);
            }
        });
        add(addOrganizationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        orgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "type", "name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 267, 520, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationButtonActionPerformed
        // TODO add your handling code here:
        String type =(String) typeComboBox.getSelectedItem();
        String name= organizationNameField.getText();

        OrganizationDirectory ogDir=this.currentEnterprise.getOrganizationDirectory();

        ogDir.addOrganization(type, name);
        JOptionPane.showMessageDialog(null, "Organization Added.");
        populate();

    }//GEN-LAST:event_addOrganizationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganizationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orgTable;
    private javax.swing.JTextField organizationNameField;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
